name: AdaWorship
favicon: null
layout_spectrum: 0.23896700888872147
typography_spectrum: 0.5634338029194623
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6373840817250311
  lightness: 0.9082347170915455
  saturation: 0.3310649381019175
  rhythmicContrast: 0.61554263276048
purpose: []
